# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb8d27eab49d09d1836acce5e76040a5cf5bdba566424c6dd6381139f89f643c81d34b393831fff6e034a0cd186d2fb87d32cd7bd417f125f254539abc80179a

test:
  secret_key_base: 1de5e3ec01fa41f05485c8306e2f964acf99cdb50bbb6e3f29ad1e60709175c869729f23afa38425fc5b3129324e3d5e20ab7c3eb7a3d4c221b7b22b26e1ab63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
